#!/bin/bash

# calculates auc over several seeded sets as generated by multiseed.sh #
# input: [directory containing folders of .total] [shift] [step]

seeds=( "ALPHA" "BRAVO" "CHARLIE" "DELTA" "ECHO" "FOXTROT" "GOLF" "HOTEL" "INDIA" "JULIETT" )
for s in "${seeds[@]}"
do
  ./auc.sh $1$s/treeinfo/ $2 $3
  mv auc.info $s.auc.info
  mv auc.ave.info $s.auc.ave.info
done
